/**
 * GitHub Actions CI/CD Generator
 * Generates GitHub Actions workflow YAML for pipeline deployment.
 */

import type { PipelineSpec } from '@eadpa/shared';

export class GitHubActionsGenerator {
  /**
   * Generate a complete CI/CD workflow for the pipeline
   */
  generate(spec: PipelineSpec): string {
    const name = spec.name;

    return `# GitHub Actions CI/CD Pipeline: ${name}
# Generated by EADPA Orchestration Engine
#
# This workflow:
# 1. Validates the pipeline YAML spec
# 2. Runs linting on generated code
# 3. Runs data quality tests against sample data
# 4. Deploys to staging (auto)
# 5. Deploys to production (manual approval)

name: "${name} - Pipeline CI/CD"

on:
  push:
    branches: [main, develop]
    paths:
      - 'pipelines/${name}/**'
      - '.github/workflows/${name}.yml'
  pull_request:
    branches: [main]
    paths:
      - 'pipelines/${name}/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - dev
          - staging
          - production

env:
  PIPELINE_NAME: ${name}
  AWS_REGION: ${spec.target.region || 'us-east-1'}
  PYTHON_VERSION: '3.11'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  validate:
    name: "Validate Pipeline Spec"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: \${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r pipelines/${name}/requirements.txt
          pip install yamllint pylint pytest

      - name: Validate YAML spec
        run: |
          yamllint pipelines/${name}/config/pipeline.yaml

      - name: Lint Python code
        run: |
          pylint pipelines/${name}/glue/ --exit-zero --disable=C,R

      - name: Validate Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5"
      - run: |
          cd pipelines/${name}/terraform
          terraform init -backend=false
          terraform validate

  test:
    name: "Run Quality Tests"
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: \${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r pipelines/${name}/requirements.txt

      - name: Run unit tests
        run: |
          cd pipelines/${name}
          pytest tests/ -v --tb=short

      - name: Run data quality checks (sample data)
        run: |
          cd pipelines/${name}
          python -m pytest tests/quality/ -v --tb=short

  deploy-staging:
    name: "Deploy to Staging"
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.event.inputs.environment == 'staging'
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ secrets.AWS_ROLE_STAGING }}
          aws-region: \${{ env.AWS_REGION }}

      - name: Upload Glue scripts to S3
        run: |
          aws s3 sync pipelines/${name}/glue/ \\
            s3://\${{ secrets.S3_BUCKET_STAGING }}/scripts/${name}/ \\
            --delete

      - name: Deploy Terraform (staging)
        run: |
          cd pipelines/${name}/terraform
          terraform init
          terraform apply -auto-approve \\
            -var="environment=staging" \\
            -var="s3_bucket_name=\${{ secrets.S3_BUCKET_STAGING }}"

      - name: Trigger staging test run
        run: |
          aws stepfunctions start-execution \\
            --state-machine-arn \${{ secrets.SFN_ARN_STAGING }} \\
            --input '{"pipeline_name":"${name}","source":"ci_staging_test"}'

  deploy-production:
    name: "Deploy to Production"
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/main' || github.event.inputs.environment == 'production'
    environment:
      name: production
      # REQUIRES MANUAL APPROVAL - matches EADPA Section 7.3
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ secrets.AWS_ROLE_PRODUCTION }}
          aws-region: \${{ env.AWS_REGION }}

      - name: Upload Glue scripts to S3
        run: |
          aws s3 sync pipelines/${name}/glue/ \\
            s3://\${{ secrets.S3_BUCKET_PRODUCTION }}/scripts/${name}/ \\
            --delete

      - name: Deploy Terraform (production)
        run: |
          cd pipelines/${name}/terraform
          terraform init
          terraform apply -auto-approve \\
            -var="environment=production" \\
            -var="s3_bucket_name=\${{ secrets.S3_BUCKET_PRODUCTION }}"

      - name: Post deployment summary
        if: always()
        run: |
          echo "## Deployment Summary" >> \$GITHUB_STEP_SUMMARY
          echo "" >> \$GITHUB_STEP_SUMMARY
          echo "- **Pipeline:** ${name}" >> \$GITHUB_STEP_SUMMARY
          echo "- **Environment:** production" >> \$GITHUB_STEP_SUMMARY
          echo "- **Region:** \${{ env.AWS_REGION }}" >> \$GITHUB_STEP_SUMMARY
          echo "- **Status:** \${{ job.status }}" >> \$GITHUB_STEP_SUMMARY
`;
  }
}
