/**
 * GitLab CI/CD Generator
 * Generates .gitlab-ci.yml for pipeline deployment.
 */

import type { PipelineSpec } from '@eadpa/shared';

export class GitLabCIGenerator {
  generate(spec: PipelineSpec): string {
    const name = spec.name;

    return `# GitLab CI/CD Pipeline: ${name}
# Generated by EADPA Orchestration Engine

stages:
  - validate
  - test
  - deploy-staging
  - deploy-production

variables:
  PIPELINE_NAME: "${name}"
  AWS_REGION: "${spec.target.region || 'us-east-1'}"
  PYTHON_VERSION: "3.11"

# Reusable templates
.python_setup: &python_setup
  image: python:\${PYTHON_VERSION}-slim
  before_script:
    - pip install -r pipelines/\${PIPELINE_NAME}/requirements.txt

# =============================================
# Stage: Validate
# =============================================
validate-yaml:
  stage: validate
  image: python:\${PYTHON_VERSION}-slim
  script:
    - pip install yamllint
    - yamllint pipelines/\${PIPELINE_NAME}/config/pipeline.yaml
  rules:
    - changes:
        - pipelines/${name}/**/*

validate-terraform:
  stage: validate
  image: hashicorp/terraform:1.5
  script:
    - cd pipelines/\${PIPELINE_NAME}/terraform
    - terraform init -backend=false
    - terraform validate
  rules:
    - changes:
        - pipelines/${name}/terraform/**/*

lint-python:
  stage: validate
  <<: *python_setup
  script:
    - pip install pylint
    - pylint pipelines/\${PIPELINE_NAME}/glue/ --exit-zero --disable=C,R
  rules:
    - changes:
        - pipelines/${name}/glue/**/*

# =============================================
# Stage: Test
# =============================================
unit-tests:
  stage: test
  <<: *python_setup
  script:
    - pip install pytest
    - cd pipelines/\${PIPELINE_NAME}
    - pytest tests/ -v --junitxml=report.xml
  artifacts:
    reports:
      junit: pipelines/\${PIPELINE_NAME}/report.xml
  rules:
    - changes:
        - pipelines/${name}/**/*

quality-tests:
  stage: test
  <<: *python_setup
  script:
    - pip install pytest great-expectations
    - cd pipelines/\${PIPELINE_NAME}
    - pytest tests/quality/ -v
  rules:
    - changes:
        - pipelines/${name}/**/*

# =============================================
# Stage: Deploy Staging (automatic)
# =============================================
deploy-staging:
  stage: deploy-staging
  image: amazon/aws-cli:latest
  environment:
    name: staging
  script:
    - aws s3 sync pipelines/\${PIPELINE_NAME}/glue/
        s3://\${S3_BUCKET_STAGING}/scripts/\${PIPELINE_NAME}/
        --delete
    - cd pipelines/\${PIPELINE_NAME}/terraform
    - terraform init
    - terraform apply -auto-approve
        -var="environment=staging"
        -var="s3_bucket_name=\${S3_BUCKET_STAGING}"
  rules:
    - if: \$CI_COMMIT_BRANCH == "main"
      changes:
        - pipelines/${name}/**/*

# =============================================
# Stage: Deploy Production (manual approval)
# =============================================
deploy-production:
  stage: deploy-production
  image: amazon/aws-cli:latest
  environment:
    name: production
  when: manual  # REQUIRES MANUAL APPROVAL (EADPA Section 7.3)
  script:
    - aws s3 sync pipelines/\${PIPELINE_NAME}/glue/
        s3://\${S3_BUCKET_PRODUCTION}/scripts/\${PIPELINE_NAME}/
        --delete
    - cd pipelines/\${PIPELINE_NAME}/terraform
    - terraform init
    - terraform apply -auto-approve
        -var="environment=production"
        -var="s3_bucket_name=\${S3_BUCKET_PRODUCTION}"
  rules:
    - if: \$CI_COMMIT_BRANCH == "main"
      changes:
        - pipelines/${name}/**/*
`;
  }
}
