/**
 * Base Compiler
 * Abstract base class with shared utilities for all compiler backends.
 * Backends extend this to get common functionality for free.
 */

import type { PipelineSpec, CloudProvider } from '@eadpa/shared';
import type {
  CompilerBackend,
  CompilationResult,
  CompilationError,
  GeneratedFile,
  CompilerOptions,
  CompilerCapabilities,
  CompilerMetadata,
  CostEstimation,
} from './interfaces';

export abstract class BaseCompiler implements CompilerBackend {
  abstract readonly id: string;
  abstract readonly name: string;
  abstract readonly provider: CloudProvider;
  abstract readonly version: string;
  abstract readonly capabilities: CompilerCapabilities;

  abstract compile(spec: PipelineSpec, options?: CompilerOptions): Promise<CompilationResult>;
  abstract validate(spec: PipelineSpec): Promise<CompilationError[]>;
  abstract estimateCost(spec: PipelineSpec): Promise<CostEstimation>;
  abstract generateInfrastructure(spec: PipelineSpec): Promise<GeneratedFile[]>;
  abstract getMetadata(): CompilerMetadata;

  /**
   * Common helper: Generate a file header comment
   */
  protected generateHeader(filename: string, spec: PipelineSpec): string {
    return [
      `# ============================================================`,
      `# Generated by EADPA - ${this.name} Backend v${this.version}`,
      `# Pipeline: ${spec.name} v${spec.version}`,
      `# Target: ${spec.target.cloud}`,
      `# Generated: ${new Date().toISOString()}`,
      `# ============================================================`,
      `# DO NOT EDIT MANUALLY - Regenerate via EADPA agent`,
      `# ============================================================`,
      '',
    ].join('\n');
  }

  /**
   * Common helper: Generate requirements/dependencies file
   */
  protected generateDependencies(deps: Record<string, string>, format: 'pip' | 'npm'): string {
    if (format === 'pip') {
      return Object.entries(deps)
        .map(([pkg, version]) => `${pkg}==${version}`)
        .join('\n');
    }
    return JSON.stringify({ dependencies: deps }, null, 2);
  }

  /**
   * Common helper: Calculate compilation result metadata
   */
  protected buildMetadata(
    files: GeneratedFile[],
    startTime: number
  ): CompilationResult['metadata'] {
    return {
      backend: this.id,
      backendVersion: this.version,
      durationMs: Date.now() - startTime,
      fileCount: files.length,
      totalSizeBytes: files.reduce((sum, f) => sum + Buffer.byteLength(f.content), 0),
      targetServices: [],
      compiledAt: new Date().toISOString(),
    };
  }

  /**
   * Common helper: Sanitize name for use in code
   */
  protected sanitizeName(name: string): string {
    return name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
  }

  /**
   * Common helper: Convert pipeline name to class name
   */
  protected toClassName(name: string): string {
    return name
      .split(/[-_\s]/)
      .map(part => part.charAt(0).toUpperCase() + part.slice(1))
      .join('');
  }

  /**
   * Common helper: Generate a config YAML from spec metadata
   */
  protected generateConfigYAML(spec: PipelineSpec): string {
    const config = {
      pipeline: spec.name,
      version: spec.version,
      owner: spec.metadata?.owner,
      schedule: spec.orchestration?.schedule,
      target_cloud: spec.target.cloud,
      target_region: spec.target.region || 'us-east-1',
    };
    return Object.entries(config)
      .filter(([_, v]) => v !== undefined)
      .map(([k, v]) => `${k}: ${v}`)
      .join('\n');
  }
}
