/**
 * Athena DDL Generator
 * Generates Athena SQL for table creation and querying.
 */

import type { PipelineSpec } from '@eadpa/shared';
import type { GeneratedFile } from '@eadpa/compiler-core';

export class AthenaGenerator {
  generate(spec: PipelineSpec): GeneratedFile[] {
    return [this.generateDDL(spec)];
  }

  private generateDDL(spec: PipelineSpec): GeneratedFile {
    const name = spec.name.replace(/-/g, '_');
    const database = `${name}_db`;
    const bucket = spec.cloud_overrides?.aws?.s3_bucket || '${S3_BUCKET}';

    let sql = `-- Athena DDL for pipeline: ${spec.name}
-- Generated by EADPA AWS Compiler
-- Run these statements to create queryable tables over the data lake

-- Create database
CREATE DATABASE IF NOT EXISTS ${database}
COMMENT 'EADPA generated database for ${spec.name}'
LOCATION 's3://${bucket}/pipelines/${name}/';

`;

    for (const layer of spec.layers) {
      const format = layer.format === 'delta' ? 'PARQUET' : layer.format.toUpperCase();
      const partition = layer.partitioning
        ? `PARTITIONED BY (${layer.partitioning.columns.map(c => `${c} STRING`).join(', ')})`
        : '';

      sql += `-- ${layer.layer.toUpperCase()} layer table
CREATE EXTERNAL TABLE IF NOT EXISTS ${database}.${name}_${layer.layer} (
    -- Column definitions will be auto-discovered from data
    -- Or specify explicit schema here
    id STRING,
    _ingested_at TIMESTAMP,
    _pipeline_run_id STRING
)
${partition}
STORED AS ${format}
LOCATION 's3://${bucket}/pipelines/${name}/${layer.layer}/${name}/'
TBLPROPERTIES (
    'classification' = '${layer.format}',
    'has_encrypted_data' = 'false',
    'pipeline' = '${spec.name}',
    'layer' = '${layer.layer}',
    'generated_by' = 'eadpa'
);

`;
    }

    // Add quarantine table
    sql += `-- Quarantine table for failed records
CREATE EXTERNAL TABLE IF NOT EXISTS ${database}.${name}_quarantine (
    id STRING,
    failure_reason STRING,
    original_record STRING,
    quarantined_at TIMESTAMP,
    pipeline_run_id STRING
)
STORED AS PARQUET
LOCATION 's3://${bucket}/pipelines/${name}/quarantine/'
TBLPROPERTIES (
    'classification' = 'parquet',
    'generated_by' = 'eadpa'
);
`;

    return {
      path: 'athena/create_tables.sql',
      content: sql,
      language: 'sql',
      description: 'Athena DDL statements for querying the data lake',
    };
  }
}
