/**
 * AWS Glue ETL Script Generator
 * Generates PySpark ETL scripts for each pipeline layer.
 */

import type { PipelineSpec, LayerConfig } from '@eadpa/shared';
import type { GeneratedFile } from '@eadpa/compiler-core';

export class GlueETLGenerator {
  generate(spec: PipelineSpec): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    for (const layer of spec.layers) {
      if (!layer.enabled) continue;

      switch (layer.layer) {
        case 'bronze':
          files.push(this.generateBronzeScript(spec, layer));
          break;
        case 'silver':
          files.push(this.generateSilverScript(spec, layer));
          break;
        case 'gold':
          files.push(this.generateGoldScript(spec, layer));
          break;
      }
    }

    // Common utilities
    files.push(this.generateUtilities(spec));

    return files;
  }

  private generateBronzeScript(spec: PipelineSpec, layer: LayerConfig): GeneratedFile {
    const name = spec.name.replace(/-/g, '_');
    const content = `"""
Bronze Layer Ingestion - ${spec.name}
Generated by EADPA AWS Compiler

Reads from source (${spec.source.type}), applies minimal transformation,
and writes to S3 in ${layer.format} format with schema enforcement.
"""

import sys
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from awsglue.context import GlueContext
from awsglue.job import Job
from awsglue.dynamicframe import DynamicFrame
from pyspark.context import SparkContext
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, current_timestamp, lit, input_file_name
from datetime import datetime
import boto3

# Initialize Glue context
args = getResolvedOptions(sys.argv, [
    'JOB_NAME',
    'source_database',
    'source_table',
    'target_path',
    'pipeline_run_id',
])

sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args['JOB_NAME'], args)

# Configuration
SOURCE_DATABASE = args['source_database']
SOURCE_TABLE = args['source_table']
TARGET_PATH = args['target_path']
PIPELINE_RUN_ID = args['pipeline_run_id']
WRITE_FORMAT = "${layer.format}"
LOAD_MODE = "${layer.load_mode}"


def read_source():
    """Read data from source system."""
    ${this.generateSourceReader(spec)}


def apply_schema_enforcement(df):
    """Apply schema enforcement rules to incoming data."""
    ${this.generateSchemaEnforcement(layer)}


def add_metadata_columns(df):
    """Add audit/metadata columns for lineage tracking."""
    return df \\
        .withColumn("_ingested_at", current_timestamp()) \\
        .withColumn("_pipeline_run_id", lit(PIPELINE_RUN_ID)) \\
        .withColumn("_source_system", lit("${spec.source.type}"))


def write_bronze(df):
    """Write data to bronze layer in ${layer.format} format."""
    writer = df.write \\
        .format("${layer.format}")${layer.partitioning ? `
    
    # Apply partitioning
    writer = writer.partitionBy(${JSON.stringify(layer.partitioning.columns)})` : ''}
    
    if LOAD_MODE == "append":
        writer.mode("append").save(f"{TARGET_PATH}/bronze/${name}")
    elif LOAD_MODE == "overwrite":
        writer.mode("overwrite").save(f"{TARGET_PATH}/bronze/${name}")
    else:
        writer.mode("append").save(f"{TARGET_PATH}/bronze/${name}")
    
    return df


def main():
    """Main ETL execution flow."""
    print(f"[EADPA] Starting Bronze ingestion for ${spec.name}")
    print(f"[EADPA] Pipeline Run ID: {PIPELINE_RUN_ID}")
    print(f"[EADPA] Target: {TARGET_PATH}/bronze/${name}")
    
    # Read from source
    source_df = read_source()
    record_count = source_df.count()
    print(f"[EADPA] Source records read: {record_count}")
    
    # Apply schema enforcement
    enforced_df = apply_schema_enforcement(source_df)
    
    # Add metadata columns
    enriched_df = add_metadata_columns(enforced_df)
    
    # Write to bronze layer
    write_bronze(enriched_df)
    
    print(f"[EADPA] Bronze ingestion complete. Records written: {record_count}")
    
    # Emit metrics
    emit_metrics(record_count)


def emit_metrics(record_count):
    """Emit pipeline metrics to CloudWatch."""
    try:
        cloudwatch = boto3.client('cloudwatch')
        cloudwatch.put_metric_data(
            Namespace='EADPA/Pipelines',
            MetricData=[
                {
                    'MetricName': 'RecordsIngested',
                    'Dimensions': [
                        {'Name': 'Pipeline', 'Value': '${spec.name}'},
                        {'Name': 'Layer', 'Value': 'bronze'},
                    ],
                    'Value': record_count,
                    'Unit': 'Count',
                },
            ]
        )
    except Exception as e:
        print(f"[EADPA] Warning: Failed to emit metrics: {e}")


if __name__ == "__main__":
    main()
    job.commit()
`;

    return {
      path: `glue/bronze_ingestion.py`,
      content,
      language: 'python',
      entryPoint: true,
      description: 'Bronze layer ingestion - raw data from source to S3',
    };
  }

  private generateSilverScript(spec: PipelineSpec, layer: LayerConfig): GeneratedFile {
    const name = spec.name.replace(/-/g, '_');
    const content = `"""
Silver Layer Transformation - ${spec.name}
Generated by EADPA AWS Compiler

Reads from bronze layer, applies data cleansing, deduplication,
type casting, and business rules. Writes to silver layer.
"""

import sys
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from awsglue.context import GlueContext
from awsglue.job import Job
from pyspark.context import SparkContext
from pyspark.sql import SparkSession, Window
from pyspark.sql.functions import (
    col, current_timestamp, lit, row_number,
    when, trim, lower, upper, coalesce
)
from datetime import datetime

# Initialize
args = getResolvedOptions(sys.argv, [
    'JOB_NAME',
    'source_path',
    'target_path',
    'pipeline_run_id',
])

sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args['JOB_NAME'], args)

SOURCE_PATH = args['source_path']
TARGET_PATH = args['target_path']
PIPELINE_RUN_ID = args['pipeline_run_id']


def read_bronze():
    """Read data from bronze layer."""
    return spark.read.format("${layer.format}").load(f"{SOURCE_PATH}/bronze/${name}")


def deduplicate(df):
    """Remove duplicate records based on configured dedup strategy."""
${this.generateDedupLogic(layer)}


def apply_transformations(df):
    """Apply data cleansing and transformation rules."""
${this.generateTransformations(layer)}


def apply_null_handling(df):
    """Handle null values per configured rules."""
${this.generateNullHandling(layer)}


def write_silver(df):
    """Write cleansed data to silver layer."""
    ${layer.load_mode === 'merge' ? `
    # Merge/Upsert logic
    from delta.tables import DeltaTable
    
    target_path = f"{TARGET_PATH}/silver/${name}"
    
    try:
        delta_table = DeltaTable.forPath(spark, target_path)
        delta_table.alias("target").merge(
            df.alias("source"),
            "target.id = source.id"
        ).whenMatchedUpdateAll() \\
         .whenNotMatchedInsertAll() \\
         .execute()
    except Exception:
        # First run - create new table
        df.write.format("delta").mode("overwrite").save(target_path)
    ` : `
    df.write \\
        .format("${layer.format}") \\
        .mode("${layer.load_mode}") \\
        .save(f"{TARGET_PATH}/silver/${name}")
    `}
    return df


def main():
    """Main silver transformation flow."""
    print(f"[EADPA] Starting Silver transformation for ${spec.name}")
    
    # Read bronze data
    bronze_df = read_bronze()
    print(f"[EADPA] Bronze records read: {bronze_df.count()}")
    
    # Deduplicate
    deduped_df = deduplicate(bronze_df)
    
    # Apply transformations
    transformed_df = apply_transformations(deduped_df)
    
    # Handle nulls
    clean_df = apply_null_handling(transformed_df)
    
    # Write to silver
    write_silver(clean_df)
    
    print(f"[EADPA] Silver transformation complete")


if __name__ == "__main__":
    main()
    job.commit()
`;

    return {
      path: 'glue/silver_transform.py',
      content,
      language: 'python',
      description: 'Silver layer - data cleansing, dedup, transformations',
    };
  }

  private generateGoldScript(spec: PipelineSpec, layer: LayerConfig): GeneratedFile {
    const name = spec.name.replace(/-/g, '_');
    const content = `"""
Gold Layer Aggregation - ${spec.name}
Generated by EADPA AWS Compiler

Reads from silver layer, applies business logic, aggregations,
and dimensional modeling. Produces business-ready datasets.
"""

import sys
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from awsglue.context import GlueContext
from awsglue.job import Job
from pyspark.context import SparkContext
from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    col, sum, count, avg, max, min,
    current_timestamp, lit, date_format
)
from datetime import datetime

# Initialize
args = getResolvedOptions(sys.argv, [
    'JOB_NAME',
    'source_path',
    'target_path',
    'pipeline_run_id',
])

sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args['JOB_NAME'], args)

SOURCE_PATH = args['source_path']
TARGET_PATH = args['target_path']
PIPELINE_RUN_ID = args['pipeline_run_id']


def read_silver():
    """Read data from silver layer."""
    return spark.read.format("${layer.format}").load(f"{SOURCE_PATH}/silver/${name}")


def apply_business_logic(df):
    """Apply business rules and aggregations for gold layer."""
    # Add business-ready transformations here
    result = df.withColumn("_gold_processed_at", current_timestamp())
    return result


def write_gold(df):
    """Write business-ready data to gold layer."""
    df.write \\
        .format("${layer.format}") \\
        .mode("${layer.load_mode}")${layer.partitioning ? ` \\
        .partitionBy(${JSON.stringify(layer.partitioning.columns)})` : ''} \\
        .save(f"{TARGET_PATH}/gold/${name}")
    return df


def main():
    """Main gold aggregation flow."""
    print(f"[EADPA] Starting Gold aggregation for ${spec.name}")
    
    # Read silver data
    silver_df = read_silver()
    print(f"[EADPA] Silver records read: {silver_df.count()}")
    
    # Apply business logic
    gold_df = apply_business_logic(silver_df)
    
    # Write to gold
    write_gold(gold_df)
    
    final_count = gold_df.count()
    print(f"[EADPA] Gold aggregation complete. Records: {final_count}")


if __name__ == "__main__":
    main()
    job.commit()
`;

    return {
      path: 'glue/gold_aggregate.py',
      content,
      language: 'python',
      description: 'Gold layer - business aggregations and dimensional modeling',
    };
  }

  private generateUtilities(spec: PipelineSpec): GeneratedFile {
    const content = `"""
Shared Utilities - ${spec.name}
Generated by EADPA AWS Compiler
"""

import boto3
import json
from datetime import datetime


def get_secret(secret_name: str, region: str = "us-east-1") -> dict:
    """Retrieve a secret from AWS Secrets Manager.
    
    SECURITY NOTE: Credentials are never hardcoded or passed through the LLM.
    They are resolved at runtime from Secrets Manager.
    """
    client = boto3.client('secretsmanager', region_name=region)
    response = client.get_secret_value(SecretId=secret_name)
    return json.loads(response['SecretString'])


def get_connection_string(secret_ref: str) -> str:
    """Build a JDBC connection string from a secret reference."""
    secret = get_secret(secret_ref)
    return (
        f"jdbc:{secret['engine']}://{secret['host']}:{secret['port']}"
        f"/{secret['database']}"
    )


def emit_pipeline_event(pipeline_name: str, event_type: str, details: dict):
    """Emit a pipeline lifecycle event to EventBridge."""
    try:
        client = boto3.client('events')
        client.put_events(
            Entries=[{
                'Source': 'eadpa.pipeline',
                'DetailType': event_type,
                'Detail': json.dumps({
                    'pipeline': pipeline_name,
                    'timestamp': datetime.utcnow().isoformat(),
                    **details,
                }),
            }]
        )
    except Exception as e:
        print(f"[EADPA] Warning: Failed to emit event: {e}")


def check_budget_guardrail(pipeline_name: str, estimated_cost: float) -> bool:
    """Check if execution is within budget guardrails."""
    # TODO: Check against DynamoDB guardrails table
    MAX_COST_PER_RUN = 50.0  # USD
    if estimated_cost > MAX_COST_PER_RUN:
        raise RuntimeError(
            f"Estimated cost (${estimated_cost:.2f}) exceeds guardrail "
            f"(${MAX_COST_PER_RUN:.2f}). Execution blocked."
        )
    return True
`;

    return {
      path: 'glue/utils.py',
      content,
      language: 'python',
      description: 'Shared utilities for secrets, metrics, and guardrails',
    };
  }

  private generateSourceReader(spec: PipelineSpec): string {
    switch (spec.source.type) {
      case 'postgres':
      case 'mysql':
      case 'sqlserver':
        return `
    # Read from JDBC source
    secret = get_secret("${spec.source.connection.secret_ref}")
    jdbc_url = f"jdbc:{secret['engine']}://{secret['host']}:{secret['port']}/{secret['database']}"
    
    df = spark.read \\
        .format("jdbc") \\
        .option("url", jdbc_url) \\
        .option("dbtable", "${spec.source.connection.table || spec.source.connection.query || 'source_table'}") \\
        .option("user", secret['username']) \\
        .option("password", secret['password']) \\
        .load()
    
    return df`;

      case 's3':
      case 'csv':
      case 'parquet':
        return `
    # Read from S3 file source
    source_path = "${spec.source.connection.path || 's3://source-bucket/data/'}"
    file_format = "${spec.source.type === 'csv' ? 'csv' : 'parquet'}"
    
    df = spark.read \\
        .format(file_format) \\
        .option("header", "true") \\
        .option("inferSchema", "true") \\
        .load(source_path)
    
    return df`;

      case 'kafka':
      case 'kinesis':
        return `
    # Read from streaming source (batch mode for ETL)
    df = spark.read \\
        .format("${spec.source.type}") \\
        .option("subscribe", "${spec.source.connection.table || 'topic'}") \\
        .load()
    
    return df`;

      default:
        return `
    # Read from Glue Data Catalog
    dynamic_frame = glueContext.create_dynamic_frame.from_catalog(
        database=SOURCE_DATABASE,
        table_name=SOURCE_TABLE,
    )
    return dynamic_frame.toDF()`;
    }
  }

  private generateSchemaEnforcement(layer: LayerConfig): string {
    if (!layer.schema_enforcement) {
      return `    return df  # No schema enforcement configured`;
    }

    const mode = layer.schema_enforcement.mode;
    if (mode === 'strict') {
      return `
    # Strict mode: reject records that don't match expected schema
    # Type coercion disabled - data must match exactly
    return df`;
    }

    return `
    # Permissive mode: allow extra columns, log warnings
    return df`;
  }

  private generateDedupLogic(layer: LayerConfig): string {
    if (!layer.dedup?.enabled) {
      return `    return df  # No deduplication configured`;
    }

    const cols = layer.dedup.columns.map(c => `"${c}"`).join(', ');
    const orderBy = layer.dedup.order_by || '_ingested_at';
    const strategy = layer.dedup.strategy === 'last' ? 'desc' : 'asc';

    return `
    # Deduplicate based on: ${layer.dedup.columns.join(', ')}
    window = Window.partitionBy(${cols}).orderBy(col("${orderBy}").${strategy}())
    
    deduped = df.withColumn("_row_num", row_number().over(window)) \\
        .filter(col("_row_num") == 1) \\
        .drop("_row_num")
    
    removed = df.count() - deduped.count()
    print(f"[EADPA] Removed {removed} duplicate records")
    
    return deduped`;
  }

  private generateTransformations(layer: LayerConfig): string {
    if (!layer.transformations || layer.transformations.length === 0) {
      return `    return df  # No transformations configured`;
    }

    let code = '    result = df\n';
    for (const transform of layer.transformations) {
      switch (transform.type) {
        case 'rename':
          const renames = transform.config as Record<string, string>;
          for (const [from, to] of Object.entries(renames)) {
            code += `    result = result.withColumnRenamed("${from}", "${to}")\n`;
          }
          break;
        case 'cast':
          const casts = transform.config as Record<string, string>;
          for (const [col_name, type] of Object.entries(casts)) {
            code += `    result = result.withColumn("${col_name}", col("${col_name}").cast("${type}"))\n`;
          }
          break;
        case 'filter':
          code += `    result = result.filter("${transform.config.expression || 'true'}")\n`;
          break;
        default:
          code += `    # TODO: Implement ${transform.type} transformation\n`;
      }
    }
    code += '    return result';
    return code;
  }

  private generateNullHandling(layer: LayerConfig): string {
    const nullConfig = layer.schema_enforcement?.null_rejection;
    if (!nullConfig) {
      return `    return df  # No null handling configured`;
    }

    const cols = nullConfig.columns.map(c => `"${c}"`).join(', ');
    if (nullConfig.action === 'reject') {
      return `
    # Reject records with null values in required columns
    required_columns = [${cols}]
    clean_df = df
    for col_name in required_columns:
        clean_df = clean_df.filter(col(col_name).isNotNull())
    
    rejected = df.count() - clean_df.count()
    if rejected > 0:
        print(f"[EADPA] Rejected {rejected} records with null values")
    
    return clean_df`;
    }

    return `
    # Quarantine records with null values
    required_columns = [${cols}]
    from functools import reduce
    from pyspark.sql.functions import isnull
    
    null_condition = reduce(
        lambda a, b: a | b,
        [isnull(col(c)) for c in required_columns]
    )
    
    quarantine_df = df.filter(null_condition)
    clean_df = df.filter(~null_condition)
    
    if quarantine_df.count() > 0:
        quarantine_df.write.format("parquet").mode("append") \\
            .save(f"{TARGET_PATH}/quarantine/${layer.layer}")
        print(f"[EADPA] Quarantined {quarantine_df.count()} records")
    
    return clean_df`;
  }
}
