/**
 * Lambda Function Generator
 * Generates Lambda handlers for pipeline triggers and utilities.
 */

import type { PipelineSpec } from '@eadpa/shared';
import type { GeneratedFile } from '@eadpa/compiler-core';

export class LambdaGenerator {
  generate(spec: PipelineSpec): GeneratedFile[] {
    return [
      this.generateTriggerFunction(spec),
      this.generateInitFunction(spec),
    ];
  }

  private generateTriggerFunction(spec: PipelineSpec): GeneratedFile {
    const name = spec.name.replace(/-/g, '_');
    const content = `"""
Pipeline Trigger Lambda - ${spec.name}
Generated by EADPA AWS Compiler

Triggers the Step Functions workflow for this pipeline.
Can be invoked by: EventBridge schedule, API Gateway, S3 event, or manual.
"""

import json
import os
import uuid
from datetime import datetime
import boto3

sfn_client = boto3.client('stepfunctions')

STATE_MACHINE_ARN = os.environ['STATE_MACHINE_ARN']
PIPELINE_NAME = "${spec.name}"
PIPELINE_VERSION = "${spec.version}"


def handler(event, context):
    """Lambda handler - triggers pipeline execution."""
    
    run_id = str(uuid.uuid4())
    trigger_source = event.get('source', 'manual')
    
    print(f"[EADPA] Triggering pipeline: {PIPELINE_NAME}")
    print(f"[EADPA] Run ID: {run_id}")
    print(f"[EADPA] Trigger: {trigger_source}")
    
    # Build execution input
    execution_input = {
        "pipeline_name": PIPELINE_NAME,
        "pipeline_version": PIPELINE_VERSION,
        "run_id": run_id,
        "triggered_by": trigger_source,
        "triggered_at": datetime.utcnow().isoformat(),
        "config": {
            "source_type": "${spec.source.type}",
            "target_cloud": "aws",
            "incremental": ${spec.source.incremental?.enabled ? 'True' : 'False'},
        },
    }
    
    # Start Step Functions execution
    response = sfn_client.start_execution(
        stateMachineArn=STATE_MACHINE_ARN,
        name=f"{PIPELINE_NAME}-{run_id[:8]}",
        input=json.dumps(execution_input),
    )
    
    execution_arn = response['executionArn']
    print(f"[EADPA] Execution started: {execution_arn}")
    
    return {
        'statusCode': 200,
        'body': json.dumps({
            'pipeline': PIPELINE_NAME,
            'run_id': run_id,
            'execution_arn': execution_arn,
            'status': 'started',
        }),
    }
`;

    return {
      path: 'lambda/trigger.py',
      content,
      language: 'python',
      description: 'Lambda function to trigger pipeline execution',
    };
  }

  private generateInitFunction(spec: PipelineSpec): GeneratedFile {
    const name = spec.name.replace(/-/g, '_');
    const content = `"""
Pipeline Initializer Lambda - ${spec.name}
Generated by EADPA AWS Compiler

Called at the start of each pipeline run to set up paths,
validate configuration, and record the execution start.
"""

import json
import os
from datetime import datetime
import boto3

s3_client = boto3.client('s3')
dynamodb = boto3.resource('dynamodb')

BUCKET = os.environ.get('S3_BUCKET', '${spec.cloud_overrides?.aws?.s3_bucket || "eadpa-data-lake"}')
EXECUTIONS_TABLE = os.environ.get('EXECUTIONS_TABLE', 'eadpa-executions')


def handler(event, context):
    """Initialize pipeline execution."""
    
    pipeline_name = event['pipeline_name']
    run_id = event['run_id']
    
    # Set up target paths
    target_path = f"s3://{BUCKET}/pipelines/{pipeline_name}"
    
    # Record execution start in DynamoDB
    table = dynamodb.Table(EXECUTIONS_TABLE)
    table.put_item(Item={
        'pipeline_name': pipeline_name,
        'run_id': run_id,
        'status': 'running',
        'started_at': datetime.utcnow().isoformat(),
        'target_path': target_path,
    })
    
    return {
        'run_id': run_id,
        'target_path': target_path,
        'bucket': BUCKET,
        'pipeline_name': pipeline_name,
        'initialized_at': datetime.utcnow().isoformat(),
    }
`;

    return {
      path: 'lambda/init_pipeline.py',
      content,
      language: 'python',
      description: 'Lambda function to initialize pipeline execution context',
    };
  }
}
