/**
 * S3 Layout Generator
 * Generates S3 path structure and lifecycle configuration.
 */

import type { PipelineSpec } from '@eadpa/shared';
import type { GeneratedFile } from '@eadpa/compiler-core';

export class S3LayoutGenerator {
  generate(spec: PipelineSpec): GeneratedFile[] {
    return [
      this.generateLayoutConfig(spec),
    ];
  }

  private generateLayoutConfig(spec: PipelineSpec): GeneratedFile {
    const name = spec.name.replace(/-/g, '_');
    const bucket = spec.cloud_overrides?.aws?.s3_bucket || '${S3_BUCKET}';

    const content = `# S3 Data Lake Layout Configuration
# Generated by EADPA for pipeline: ${spec.name}
#
# Layout follows the medallion architecture pattern:
# s3://<bucket>/pipelines/<pipeline_name>/<layer>/<table>/
#
# With Hive-compatible partitioning:
# s3://<bucket>/pipelines/<pipeline_name>/<layer>/<table>/year=YYYY/month=MM/day=DD/

layout:
  bucket: ${bucket}
  prefix: pipelines/${name}
  
  layers:
    bronze:
      path: pipelines/${name}/bronze
      format: ${spec.layers.find(l => l.layer === 'bronze')?.format || 'parquet'}
      compression: snappy
      lifecycle:
        transition_to_ia_days: 30
        transition_to_glacier_days: 90
        expiration_days: 365
    
    silver:
      path: pipelines/${name}/silver
      format: ${spec.layers.find(l => l.layer === 'silver')?.format || 'delta'}
      compression: snappy
      lifecycle:
        transition_to_ia_days: 60
        expiration_days: 730
    
    gold:
      path: pipelines/${name}/gold
      format: ${spec.layers.find(l => l.layer === 'gold')?.format || 'delta'}
      compression: snappy
      lifecycle:
        # Gold data retained indefinitely
        transition_to_ia_days: 180
    
    quarantine:
      path: pipelines/${name}/quarantine
      format: parquet
      lifecycle:
        expiration_days: ${spec.quality?.quarantine?.retention_days || 30}
  
  metadata:
    path: pipelines/${name}/_metadata
    catalog_database: ${name}_db
    
  checkpoints:
    path: pipelines/${name}/_checkpoints
`;

    return {
      path: 'config/s3-layout.yaml',
      content,
      language: 'yaml',
      description: 'S3 data lake layout and lifecycle configuration',
    };
  }
}
