/**
 * Terraform Generator
 * Generates infrastructure-as-code for AWS resources.
 */

import type { PipelineSpec } from '@eadpa/shared';
import type { GeneratedFile } from '@eadpa/compiler-core';

export class TerraformGenerator {
  generate(spec: PipelineSpec): GeneratedFile[] {
    return [
      this.generateMain(spec),
      this.generateVariables(spec),
      this.generateOutputs(spec),
    ];
  }

  private generateMain(spec: PipelineSpec): GeneratedFile {
    const name = spec.name.replace(/-/g, '_');
    const region = spec.target.region || 'us-east-1';

    const content = `# Terraform Configuration for ${spec.name}
# Generated by EADPA AWS Compiler
# 
# This creates all AWS resources needed to run the pipeline.

terraform {
  required_version = ">= 1.5.0"
  
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  
  backend "s3" {
    bucket = var.terraform_state_bucket
    key    = "pipelines/${name}/terraform.tfstate"
    region = "${region}"
  }
}

provider "aws" {
  region = var.aws_region
  
  default_tags {
    tags = {
      Pipeline    = "${spec.name}"
      ManagedBy   = "eadpa-terraform"
      Environment = var.environment
    }
  }
}

# ==========================================
# S3 Data Lake Bucket
# ==========================================

resource "aws_s3_bucket" "data_lake" {
  bucket = var.s3_bucket_name
}

resource "aws_s3_bucket_versioning" "data_lake" {
  bucket = aws_s3_bucket.data_lake.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "data_lake" {
  bucket = aws_s3_bucket.data_lake.id
  
  rule {
    id     = "bronze-lifecycle"
    status = "Enabled"
    filter { prefix = "pipelines/${name}/bronze/" }
    transition {
      days          = 30
      storage_class = "STANDARD_IA"
    }
    transition {
      days          = 90
      storage_class = "GLACIER"
    }
  }
  
  rule {
    id     = "quarantine-lifecycle"
    status = "Enabled"
    filter { prefix = "pipelines/${name}/quarantine/" }
    expiration { days = ${spec.quality?.quarantine?.retention_days || 30} }
  }
}

# ==========================================
# Glue Jobs
# ==========================================

resource "aws_glue_catalog_database" "pipeline_db" {
  name = "${name}_db"
}

resource "aws_glue_job" "bronze" {
  name     = "${name}_bronze"
  role_arn = aws_iam_role.glue_role.arn
  
  command {
    name            = "glueetl"
    script_location = "s3://\${aws_s3_bucket.data_lake.id}/scripts/${name}/bronze_ingestion.py"
    python_version  = "3"
  }
  
  glue_version      = "${spec.cloud_overrides?.aws?.glue_version || '4.0'}"
  number_of_workers = ${spec.cloud_overrides?.aws?.glue_workers || 2}
  worker_type       = "G.1X"
  timeout           = ${spec.orchestration?.timeout_minutes || 60}
  
  default_arguments = {
    "--job-language"              = "python"
    "--enable-continuous-cloudwatch-log" = "true"
    "--enable-metrics"            = "true"
    "--additional-python-modules" = "delta-spark==2.4.0"
  }
}

resource "aws_glue_job" "silver" {
  name     = "${name}_silver"
  role_arn = aws_iam_role.glue_role.arn
  
  command {
    name            = "glueetl"
    script_location = "s3://\${aws_s3_bucket.data_lake.id}/scripts/${name}/silver_transform.py"
    python_version  = "3"
  }
  
  glue_version      = "${spec.cloud_overrides?.aws?.glue_version || '4.0'}"
  number_of_workers = ${spec.cloud_overrides?.aws?.glue_workers || 2}
  worker_type       = "G.1X"
  timeout           = ${spec.orchestration?.timeout_minutes || 60}
}

resource "aws_glue_job" "gold" {
  name     = "${name}_gold"
  role_arn = aws_iam_role.glue_role.arn
  
  command {
    name            = "glueetl"
    script_location = "s3://\${aws_s3_bucket.data_lake.id}/scripts/${name}/gold_aggregate.py"
    python_version  = "3"
  }
  
  glue_version      = "${spec.cloud_overrides?.aws?.glue_version || '4.0'}"
  number_of_workers = ${spec.cloud_overrides?.aws?.glue_workers || 2}
  worker_type       = "G.1X"
  timeout           = ${spec.orchestration?.timeout_minutes || 60}
}

# ==========================================
# Step Functions State Machine
# ==========================================

resource "aws_sfn_state_machine" "pipeline" {
  name     = "${name}_workflow"
  role_arn = aws_iam_role.sfn_role.arn
  
  definition = file("\${path.module}/../step_functions/workflow.asl.json")
}

# ==========================================
# EventBridge Schedule (if scheduled)
# ==========================================

resource "aws_scheduler_schedule" "pipeline_schedule" {
  name       = "${name}_schedule"
  group_name = "eadpa-pipelines"
  
  schedule_expression = "cron(${this.cronToAWS(spec.orchestration?.schedule)})"
  
  flexible_time_window {
    mode = "OFF"
  }
  
  target {
    arn      = aws_sfn_state_machine.pipeline.arn
    role_arn = aws_iam_role.scheduler_role.arn
    
    input = jsonencode({
      pipeline_name    = "${spec.name}"
      pipeline_version = "${spec.version}"
      source           = "scheduled"
    })
  }
}

# ==========================================
# IAM Roles
# ==========================================

resource "aws_iam_role" "glue_role" {
  name = "eadpa-${name}-glue-role"
  
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "glue.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role_policy_attachment" "glue_service" {
  role       = aws_iam_role.glue_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
}

resource "aws_iam_role" "sfn_role" {
  name = "eadpa-${name}-sfn-role"
  
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "states.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role" "scheduler_role" {
  name = "eadpa-${name}-scheduler-role"
  
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "scheduler.amazonaws.com" }
    }]
  })
}
`;

    return {
      path: 'terraform/main.tf',
      content,
      language: 'hcl',
      description: 'Main Terraform configuration for all pipeline resources',
    };
  }

  private generateVariables(spec: PipelineSpec): GeneratedFile {
    const content = `# Terraform Variables for ${spec.name}
# Generated by EADPA AWS Compiler

variable "aws_region" {
  description = "AWS region for deployment"
  type        = string
  default     = "${spec.target.region || 'us-east-1'}"
}

variable "environment" {
  description = "Deployment environment (dev, staging, production)"
  type        = string
  default     = "dev"
}

variable "s3_bucket_name" {
  description = "S3 bucket name for the data lake"
  type        = string
}

variable "terraform_state_bucket" {
  description = "S3 bucket for Terraform state"
  type        = string
}
`;

    return {
      path: 'terraform/variables.tf',
      content,
      language: 'hcl',
      description: 'Terraform input variables',
    };
  }

  private generateOutputs(spec: PipelineSpec): GeneratedFile {
    const content = `# Terraform Outputs for ${spec.name}
# Generated by EADPA AWS Compiler

output "state_machine_arn" {
  description = "ARN of the Step Functions state machine"
  value       = aws_sfn_state_machine.pipeline.arn
}

output "s3_bucket_name" {
  description = "Name of the data lake S3 bucket"
  value       = aws_s3_bucket.data_lake.id
}

output "glue_database" {
  description = "Name of the Glue catalog database"
  value       = aws_glue_catalog_database.pipeline_db.name
}

output "pipeline_schedule" {
  description = "ARN of the EventBridge schedule"
  value       = aws_scheduler_schedule.pipeline_schedule.arn
}
`;

    return {
      path: 'terraform/outputs.tf',
      content,
      language: 'hcl',
      description: 'Terraform outputs',
    };
  }

  private cronToAWS(cron?: string): string {
    if (!cron) return '0 6 * * ? *';
    // Convert standard cron to AWS cron (6 fields with year)
    const parts = cron.split(' ');
    if (parts.length === 5) {
      return `${parts[0]} ${parts[1]} ${parts[2]} ${parts[3]} ? *`;
    }
    return cron;
  }
}
