/**
 * Quality Check Generator
 * Generates data quality check definitions based on schema analysis,
 * user requirements, and best practices.
 */

import type { SourceColumn } from '@eadpa/shared';
import type {
  QualityCheckDefinition,
  SchemaCheckConfig,
  NullCheckConfig,
  UniqueCheckConfig,
  RangeCheckConfig,
  PatternCheckConfig,
  FreshnessCheckConfig,
  VolumeCheckConfig,
} from '@eadpa/shared';
import { v4 as uuidv4 } from 'uuid';

export interface GenerateChecksOptions {
  /** Layer this check applies to */
  layer: 'bronze' | 'silver' | 'gold' | 'all';
  /** Whether to generate checks for all columns or just key columns */
  scope: 'comprehensive' | 'essential' | 'minimal';
  /** Include freshness checks */
  includeFreshness: boolean;
  /** Include volume anomaly detection */
  includeVolume: boolean;
  /** Custom business rules to include */
  businessRules?: string[];
}

export class QualityCheckGenerator {
  /**
   * Auto-generate quality checks from schema metadata
   */
  generateFromSchema(
    columns: SourceColumn[],
    options: Partial<GenerateChecksOptions> = {}
  ): QualityCheckDefinition[] {
    const opts: GenerateChecksOptions = {
      layer: 'all',
      scope: 'comprehensive',
      includeFreshness: true,
      includeVolume: true,
      ...options,
    };

    const checks: QualityCheckDefinition[] = [];

    // 1. Schema validation check
    checks.push(this.generateSchemaCheck(columns, opts.layer));

    // 2. Null checks for non-nullable columns
    const nonNullColumns = columns.filter(c => !c.nullable);
    if (nonNullColumns.length > 0) {
      checks.push(this.generateNullCheck(nonNullColumns, opts.layer));
    }

    // 3. Uniqueness checks for primary keys
    const pkColumns = columns.filter(c => c.primary_key);
    if (pkColumns.length > 0) {
      checks.push(this.generateUniqueCheck(pkColumns, opts.layer));
    }

    // 4. Pattern checks for known column types
    if (opts.scope !== 'minimal') {
      const patternChecks = this.generatePatternChecks(columns, opts.layer);
      checks.push(...patternChecks);
    }

    // 5. Range checks for numeric columns
    if (opts.scope === 'comprehensive') {
      const rangeChecks = this.generateRangeChecks(columns, opts.layer);
      checks.push(...rangeChecks);
    }

    // 6. Freshness check
    if (opts.includeFreshness) {
      const timestampCol = columns.find(c =>
        /updated_at|modified_at|last_updated|timestamp/i.test(c.name)
      );
      if (timestampCol) {
        checks.push(this.generateFreshnessCheck(timestampCol.name, opts.layer));
      }
    }

    // 7. Volume check
    if (opts.includeVolume) {
      checks.push(this.generateVolumeCheck(opts.layer));
    }

    return checks;
  }

  /**
   * Generate a Great Expectations-compatible test suite
   */
  generateGreatExpectationsSuite(
    checks: QualityCheckDefinition[],
    suiteName: string
  ): string {
    const expectations = checks.map(check => this.toGreatExpectation(check));

    return JSON.stringify({
      expectation_suite_name: suiteName,
      meta: {
        generated_by: 'eadpa-quality-engine',
        generated_at: new Date().toISOString(),
      },
      expectations,
    }, null, 2);
  }

  /**
   * Generate dbt test YAML
   */
  generateDbtTests(
    checks: QualityCheckDefinition[],
    modelName: string
  ): string {
    const lines: string[] = [
      '# Generated by EADPA Quality Engine',
      `# Data quality tests for model: ${modelName}`,
      '',
      'version: 2',
      '',
      'models:',
      `  - name: ${modelName}`,
      '    columns:',
    ];

    // Group checks by column
    const columnChecks = new Map<string, QualityCheckDefinition[]>();
    for (const check of checks) {
      const config = check.config as any;
      const cols = config.columns || config.column ? [config.column || config.columns?.[0]] : ['_table'];
      for (const col of cols) {
        const existing = columnChecks.get(col) || [];
        existing.push(check);
        columnChecks.set(col, existing);
      }
    }

    for (const [column, colChecks] of columnChecks) {
      if (column === '_table') continue;
      lines.push(`      - name: ${column}`);
      lines.push('        tests:');
      for (const check of colChecks) {
        const dbtTest = this.toDbtTest(check);
        if (dbtTest) {
          lines.push(`          - ${dbtTest}`);
        }
      }
    }

    return lines.join('\n');
  }

  private generateSchemaCheck(columns: SourceColumn[], layer: string): QualityCheckDefinition {
    const config: SchemaCheckConfig = {
      type: 'schema',
      expected_columns: columns.map(c => ({
        name: c.name,
        data_type: c.data_type,
        nullable: c.nullable,
      })),
      allow_extra_columns: layer === 'bronze', // Bronze is permissive
      strict_types: layer === 'gold', // Gold is strict
    };

    return {
      id: uuidv4(),
      name: 'schema_validation',
      description: 'Validate incoming data matches expected schema',
      type: 'schema',
      layer: layer as any,
      severity: 'critical',
      action_on_fail: 'halt_pipeline',
      config: config as any,
      enabled: true,
    };
  }

  private generateNullCheck(columns: SourceColumn[], layer: string): QualityCheckDefinition {
    const config: NullCheckConfig = {
      type: 'null',
      columns: columns.map(c => c.name),
      max_null_percentage: 0,
    };

    return {
      id: uuidv4(),
      name: 'not_null_required_columns',
      description: `Ensure required columns (${columns.map(c => c.name).join(', ')}) have no null values`,
      type: 'null',
      layer: layer as any,
      severity: 'critical',
      action_on_fail: 'quarantine_record',
      config: config as any,
      enabled: true,
    };
  }

  private generateUniqueCheck(columns: SourceColumn[], layer: string): QualityCheckDefinition {
    const config: UniqueCheckConfig = {
      type: 'unique',
      columns: columns.map(c => c.name),
      allow_nulls: false,
    };

    return {
      id: uuidv4(),
      name: 'unique_primary_keys',
      description: `Ensure primary key columns (${columns.map(c => c.name).join(', ')}) are unique`,
      type: 'unique',
      layer: layer as any,
      severity: 'critical',
      action_on_fail: 'quarantine_record',
      config: config as any,
      enabled: true,
    };
  }

  private generatePatternChecks(columns: SourceColumn[], layer: string): QualityCheckDefinition[] {
    const checks: QualityCheckDefinition[] = [];

    const patterns: Array<{ namePattern: RegExp; regex: string; description: string }> = [
      { namePattern: /email/i, regex: '^[^@]+@[^@]+\\.[^@]+$', description: 'Valid email format' },
      { namePattern: /phone|tel|mobile/i, regex: '^\\+?[0-9\\-\\s()]{7,20}$', description: 'Valid phone format' },
      { namePattern: /url|website|link/i, regex: '^https?://', description: 'Valid URL format' },
      { namePattern: /uuid|guid/i, regex: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', description: 'Valid UUID format' },
    ];

    for (const column of columns) {
      for (const { namePattern, regex, description } of patterns) {
        if (namePattern.test(column.name)) {
          const config: PatternCheckConfig = {
            type: 'pattern',
            column: column.name,
            pattern: regex,
            match_type: 'full',
          };

          checks.push({
            id: uuidv4(),
            name: `pattern_${column.name}`,
            description: `${description} for column '${column.name}'`,
            type: 'pattern',
            layer: layer as any,
            severity: 'major',
            action_on_fail: 'quarantine_record',
            config: config as any,
            enabled: true,
          });
          break;
        }
      }
    }

    return checks;
  }

  private generateRangeChecks(columns: SourceColumn[], layer: string): QualityCheckDefinition[] {
    const checks: QualityCheckDefinition[] = [];

    for (const column of columns) {
      // Age-like columns
      if (/age/i.test(column.name) && /int/i.test(column.data_type)) {
        checks.push({
          id: uuidv4(),
          name: `range_${column.name}`,
          description: `${column.name} should be within reasonable range (0-150)`,
          type: 'range',
          layer: layer as any,
          severity: 'major',
          action_on_fail: 'quarantine_record',
          config: { type: 'range', column: column.name, min: 0, max: 150, inclusive: true } as any,
          enabled: true,
        });
      }

      // Amount/price columns (should be non-negative)
      if (/amount|price|cost|fee|total|balance/i.test(column.name)) {
        checks.push({
          id: uuidv4(),
          name: `range_${column.name}`,
          description: `${column.name} should be non-negative`,
          type: 'range',
          layer: layer as any,
          severity: 'major',
          action_on_fail: 'warn_continue',
          config: { type: 'range', column: column.name, min: 0, inclusive: true } as any,
          enabled: true,
        });
      }
    }

    return checks;
  }

  private generateFreshnessCheck(columnName: string, layer: string): QualityCheckDefinition {
    const config: FreshnessCheckConfig = {
      type: 'freshness',
      timestamp_column: columnName,
      max_delay_minutes: 1440, // 24 hours
    };

    return {
      id: uuidv4(),
      name: 'data_freshness',
      description: `Data should not be more than 24 hours old (based on ${columnName})`,
      type: 'freshness',
      layer: layer as any,
      severity: 'major',
      action_on_fail: 'warn_continue',
      config: config as any,
      enabled: true,
    };
  }

  private generateVolumeCheck(layer: string): QualityCheckDefinition {
    const config: VolumeCheckConfig = {
      type: 'volume',
      min_rows: 1,
      tolerance_percentage: 50,
    };

    return {
      id: uuidv4(),
      name: 'volume_anomaly',
      description: 'Detect unusual changes in data volume (>50% deviation)',
      type: 'volume' as any,
      layer: layer as any,
      severity: 'major',
      action_on_fail: 'warn_continue',
      config: config as any,
      enabled: true,
    };
  }

  private toGreatExpectation(check: QualityCheckDefinition): Record<string, unknown> {
    const config = check.config as any;
    switch (check.type) {
      case 'null':
        return {
          expectation_type: 'expect_column_values_to_not_be_null',
          kwargs: { column: config.columns?.[0] },
        };
      case 'unique':
        return {
          expectation_type: 'expect_column_values_to_be_unique',
          kwargs: { column: config.columns?.[0] },
        };
      case 'pattern':
        return {
          expectation_type: 'expect_column_values_to_match_regex',
          kwargs: { column: config.column, regex: config.pattern },
        };
      case 'range':
        return {
          expectation_type: 'expect_column_values_to_be_between',
          kwargs: { column: config.column, min_value: config.min, max_value: config.max },
        };
      default:
        return { expectation_type: 'custom', meta: { check_name: check.name } };
    }
  }

  private toDbtTest(check: QualityCheckDefinition): string | null {
    switch (check.type) {
      case 'null': return 'not_null';
      case 'unique': return 'unique';
      case 'pattern': return `accepted_values:  # pattern: ${(check.config as any).pattern}`;
      default: return null;
    }
  }
}
