/**
 * Mapping YAML Exporter
 * Exports source-to-target mappings as YAML documents.
 */

import type { SourceToTargetMapping, ColumnMapping } from '@eadpa/shared';

export class MappingYAMLExporter {
  /**
   * Export a mapping to YAML format
   */
  export(mapping: SourceToTargetMapping): string {
    const lines: string[] = [
      `# Source-to-Target Mapping: ${mapping.name}`,
      `# Generated by EADPA Mapping Engine`,
      `# Version: ${mapping.version}`,
      `# Status: ${mapping.status}`,
      '',
      `name: ${mapping.name}`,
      `version: ${mapping.version}`,
      `status: ${mapping.status}`,
      '',
      '# Source System',
      'source:',
      `  system: ${mapping.source.system}`,
      `  type: ${mapping.source.type}`,
    ];

    if (mapping.source.database) lines.push(`  database: ${mapping.source.database}`);
    if (mapping.source.schema) lines.push(`  schema: ${mapping.source.schema}`);
    if (mapping.source.table) lines.push(`  table: ${mapping.source.table}`);

    lines.push('');
    lines.push('# Target Model');
    lines.push('target:');
    lines.push(`  model_style: ${mapping.target.model_style}`);
    lines.push('  tables:');

    for (const table of mapping.target.tables) {
      lines.push(`    - name: ${table.name}`);
      lines.push(`      type: ${table.type}`);
      lines.push(`      primary_key: [${table.primary_key.join(', ')}]`);
    }

    lines.push('');
    lines.push('# Column Mappings');
    lines.push('mappings:');

    for (const m of mapping.column_mappings) {
      lines.push(`  - source: ${m.source_column}`);
      lines.push(`    target: ${m.target_table}.${m.target_column}`);
      lines.push(`    transform: ${m.transformation.type}`);
      if (m.transformation.new_name) lines.push(`    new_name: ${m.transformation.new_name}`);
      if (m.transformation.target_type) lines.push(`    target_type: ${m.transformation.target_type}`);
      if (m.transformation.expression) lines.push(`    expression: "${m.transformation.expression}"`);
    }

    if (mapping.schema_drift_policy) {
      lines.push('');
      lines.push('# Schema Drift Policy');
      lines.push('schema_drift:');
      lines.push(`  detection_enabled: ${mapping.schema_drift_policy.detection_enabled}`);
      lines.push(`  on_new_column: ${mapping.schema_drift_policy.action_on_new_column}`);
      lines.push(`  on_removed_column: ${mapping.schema_drift_policy.action_on_removed_column}`);
      lines.push(`  on_type_change: ${mapping.schema_drift_policy.action_on_type_change}`);
    }

    return lines.join('\n');
  }
}
