'use client';

import { useState } from 'react';
import { X, Copy, Check, Download, Play, FileCode, GitBranch, Eye } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useConversationStore } from '@/store/conversation';
import { CodeBlock } from '../chat/code-block';

interface ArtifactPanelProps {
  onClose: () => void;
}

export function ArtifactPanel({ onClose }: ArtifactPanelProps) {
  const { activeArtifact } = useConversationStore();
  const [activeTab, setActiveTab] = useState<'code' | 'preview' | 'diff'>('code');
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    if (activeArtifact) {
      await navigator.clipboard.writeText(activeArtifact.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <aside className="w-[500px] border-l border-border bg-card flex flex-col h-full animate-slide-in">
      {/* Header */}
      <div className="h-12 border-b border-border flex items-center justify-between px-4 shrink-0">
        <div className="flex items-center gap-2">
          <FileCode className="h-4 w-4 text-primary" />
          <h2 className="text-sm font-medium">
            {activeArtifact?.title || 'Generated Output'}
          </h2>
          {activeArtifact?.version && (
            <span className="text-[10px] px-1.5 py-0.5 bg-accent rounded text-muted-foreground">
              v{activeArtifact.version}
            </span>
          )}
        </div>
        <div className="flex items-center gap-1">
          <button
            onClick={handleCopy}
            className="p-1.5 hover:bg-accent rounded-md transition-colors text-muted-foreground"
            title="Copy all"
          >
            {copied ? <Check className="h-4 w-4 text-green-500" /> : <Copy className="h-4 w-4" />}
          </button>
          <button
            className="p-1.5 hover:bg-accent rounded-md transition-colors text-muted-foreground"
            title="Download"
          >
            <Download className="h-4 w-4" />
          </button>
          <button
            className="p-1.5 hover:bg-accent rounded-md transition-colors text-muted-foreground"
            title="Run in sandbox"
          >
            <Play className="h-4 w-4" />
          </button>
          <button
            onClick={onClose}
            className="p-1.5 hover:bg-accent rounded-md transition-colors text-muted-foreground ml-2"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex items-center gap-0 px-4 border-b border-border">
        {[
          { id: 'code', label: 'Code', icon: FileCode },
          { id: 'preview', label: 'Preview', icon: Eye },
          { id: 'diff', label: 'Changes', icon: GitBranch },
        ].map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id as any)}
            className={cn(
              'flex items-center gap-1.5 px-3 py-2.5 text-xs font-medium border-b-2 transition-colors',
              activeTab === tab.id
                ? 'border-primary text-primary'
                : 'border-transparent text-muted-foreground hover:text-foreground'
            )}
          >
            <tab.icon className="h-3.5 w-3.5" />
            {tab.label}
          </button>
        ))}
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto">
        {activeArtifact ? (
          <div className="p-0">
            <CodeBlock
              code={activeArtifact.content}
              language={activeArtifact.language || 'text'}
              showLineNumbers
            />
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center h-full text-muted-foreground">
            <FileCode className="h-12 w-12 mb-3 opacity-30" />
            <p className="text-sm">No artifact selected</p>
            <p className="text-xs mt-1">Generated code and configs will appear here</p>
          </div>
        )}
      </div>

      {/* Footer with metadata */}
      {activeArtifact && (
        <div className="border-t border-border px-4 py-2 flex items-center justify-between text-[10px] text-muted-foreground">
          <span>{activeArtifact.language?.toUpperCase()} | {activeArtifact.content.split('\n').length} lines</span>
          <span>Generated by EADPA AWS Compiler</span>
        </div>
      )}
    </aside>
  );
}
